# Generated by Django 4.2.2 on 2023-08-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mock_exchange_app", "0004_alter_wallet_asset_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="asset",
            table="assets",
        ),
        migrations.AlterModelTable(
            name="wallet",
            table="wallets",
        ),
    ]
