# Generated by Django 4.2.2 on 2023-08-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mock_exchange_app", "0005_alter_asset_table_alter_wallet_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="wallet_address",
            field=models.CharField(
                default="bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wallet",
            name="asset_id",
            field=models.CharField(choices=[("BTC", "Bitcoin"), ("ETH", "Ethereum")]),
        ),
    ]
