# Generated by Django 4.2.2 on 2023-08-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_exchange_app", "0006_wallet_user_wallet_wallet_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="user_name",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_address",
            field=models.CharField(blank=True),
        ),
    ]
