# Generated by Django 4.2.2 on 2023-08-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_exchange_app", "0008_alter_wallet_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="asset_id",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin"),
                    ("ETH", "Ethereum"),
                    ("ETH_TEST3", "Ethereum Goerli"),
                    ("BTC_TEST", "Bitcoin Test"),
                ]
            ),
        ),
    ]
