# Generated by Django 4.2.2 on 2023-08-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_exchange_app", "0009_alter_wallet_asset_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="user_name",
            field=models.CharField(),
        ),
    ]
